### ISSUE TITLE
Everyone sets up a development environment

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/zwreec#1]
Everybody should have the Rust Compiler and Cargo installed.

**Comment by Drakulix** [comment]
Everybody posts a screenshot of his "IDE" for the slides till next week!

**Comment by Drakulix** [comment]
![screenshot from 2015-04-23 17-41-30](https://cloud.githubusercontent.com/assets/4404502/7300992/00ef6798-e9e0-11e4-8f14-6218f123a68c.png)

**Comment by msaehn** [comment]
![sublime](https://cloud.githubusercontent.com/assets/1397415/7302261/620d749a-e9e8-11e4-9314-069a02609b99.png)

**Comment by stilleben** [comment]
![screenshot-ide-im](https://cloud.githubusercontent.com/assets/11980960/7337162/3ea606dc-ec1f-11e4-9ca2-f1bf5dc92c3f.png)

**Comment by benj-zen** [comment]
![rust ide](https://cloud.githubusercontent.com/assets/5678345/7338177/21ac26d6-ec44-11e4-8481-3df8531ef4ad.png)

**Comment by pothos** [comment]
![nano](https://cloud.githubusercontent.com/assets/1189130/7346262/d9b60e66-ecdc-11e4-8674-10180c697cb8.png)

**Comment by felinira** [comment]
![screen shot 2015-04-28 at 18 40 46](https://cloud.githubusercontent.com/assets/121945/7375044/366f433a-edd6-11e4-9ab8-5683412be8c6.png)
