### ISSUE TITLE
Integrationstests sammeln

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#107]
Große (Realbeispiele) Twine-Geschichten sammeln. Für die Geschichten eine gruppenübergreifende Sammelstelle finden.
- [x] geschichten sammeln
- [x] mit den anderen gruppen abstimmen wo die geschichten hingeladen werden sollen. vorschlag kvv

**Comment by msaehn** [comment]
ich hab knapp 75 geschichten gefunden. davon werden wir wohl nur 25 unterstützen können. in der praxis werden es eher weniger werden :/

**Comment by felinira** [comment]
Woran scheitert es meistens?

**Comment by msaehn** [comment]
in etwas in der reihenfolge:
- replace macro
- eigene macros <-> java script
- inline base64-bilder (da könnte eventuell was gedreht werden)

**Comment by msaehn** [comment]
ich hab die daten erstmal in die dropbox gehauen unter Sammlung/[not_supported/should_work]

wir sollten nächste woche mit den anderen gruppen nochmal absprechen wo wir diese hochladen.
(ich hab die geschichten, die ich auf den ersten blick eindeutig als fsk18 einstufen würde, ausgelassen.)
die geschichten stammen alle aus http://ifdb.tads.org/, ich habe nur geschichten gewählt die mehr als 3 sterne haben. die wenigsten hatten eine *.twee oder *.tws datei, aber twine kann ja aus html-stories importieren, was zwar nervig war, aber ging.

**Comment by felinira** [comment]
Ich hab noch mal Depression Quest decompiled und in should-work hinzugefügt. Manches geht davon zwar nicht, wie Bilder, aber die Story dürfte trotzdem spielbar sein IMHO. Ich denke, dass das auf viele zutreffen wird.

Was hochladen angeht wird wohl nur ein privater Bereich gehen, wegen Copyright usw. Nicht so eine gute Idee, hunderte twee files öffentlich zu hosten, die wir nicht selber geschrieben haben.

**Comment by msaehn** [comment]
deshalb dachte ich vielleicht auch wir packen die nicht in das repo sondern ins kvv. das soll ja eh gruppenübergreifend gesammelt werden und dann wäre es auch nicht öffentlich.

**Comment by felinira** [comment]
Das fände ich auch sinnvoll. Aber ja, lass uns das mal Donnerstag besprechen mit den Gruppen.

**Comment by msaehn** [comment]
ich hab mir die dateien nochmal angeschaut, von 69 geschichten werden wir wohl nur 16 unterstützen können. ich vermute in der praxis fallen 2-3 zusätzlich weg. -.-

**Comment by msaehn** [comment]
hab mit den anderen gruppen gesprochen, dass es ok ist, wenn wir die geschichten ins kvv hochladen. das hab ich gemacht. damit ist hier alles erledigt.
