### ISSUE TITLE
Hilfreiche Compiler-Fehler

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#108]
Bei ungültigen .twee Dateien werden möglichst vernünftige Fehlermeldungen ausgegeben, die den Programmierenden so gut wie möglich weiterhelfen

**Comment by felinira** [comment]
In meinem Fork von rustlex https://github.com/Farthen/rustlex gibt es eine funktion yylloc() (Name angelehnt an bison), die die jeweils aktuelle Position im Input Stream zurückgibt in Zeilen und Zeichen ab Zeilenanfang. Das müsste "nur noch" jemand im Token speichern. Damit warte ich auf den Refactor von Lexer Tokens.

**Comment by msaehn** [comment]
was fehlt hier noch? (klar, hilfreicher geht immer, aber gibt es konkrete sachen die noch implementiert werden müssten?)

**Comment by felinira** [comment]
Im AST sollte noch die error-Funktion implementiert werden. Und vielleicht auch noch Zeilennummern angeben, soweit das möglich ist.

**Comment by pothos** [comment]
Zur Zeit gibt es einen Absturz bei Links zu fehlenden Passagen in zfile.write_jumps, wobei dies aber auch schon direkt nach dem Lexen geprüft werden könnte mit einer ordentlichen Fehlermeldung.

**Comment by msaehn** [comment]
dafür gibt es auch im CodeGenManager einen vec<String> der alle existierenden passagenamen enthält. der müsste nur im ast beim der erstellung von links bzw. display überprüft werden.

**Comment by msaehn** [comment]
da dies der letzte offene milestone ist. gibt es eine person die sich da berufen fühlt die passage schon im ast zu überprüfen und eine sinnvolle fehlermeldung auszugeben? und danach würde ich vorschlagen den dann als backlog-item erstmal zu schließen. für die abschlußpräsentation müssten wir uns eh nochmal anschauen was wir erledigen sollten und was nicht.

**Comment by felinira** [comment]
Mit #207 ist der AST jetzt auch immerhin so weit, dass der ne cfg bekommt während er gebaut wird und diese cfg auch an den expressionparser weiter geben kann. Damit können wir an diesen Orten bessere Fehlermeldungen ausgeben und eben auch genau sowas machen. Ich kann mich gerne drum kümmern, dass das hier auch passiert.
