### ISSUE TITLE
Makro display

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#116]
wird benötigt für #114 . in zcode sollte dafür eigentlich alles bereitstehen. es müsste wohl aber die check_links routine verändert werden, die überprüft ob die aufgerufene passage normal aufgerufen wird, oder via display. wenn sie mit display aufgerufen wird, dann solle die check_links-routine übersprungen.

**Comment by stilleben** [comment]
2e524e7 müsste rückgängig gemacht werden bzw. der auskommentierte Test müsste angepasst werden, wenn das hier implementiert ist.
