### ISSUE TITLE
wenn variable nicht gesetzt ist, stürzt der compiler ab

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#137]
das sollte aber wohl nicht passieren.
'''
panicked at 'called Option::unwrap() on a None value'
'''

bsp:

```
::Start
<<$test>>
```

zu klären ist wie twee das löst. demensprechend oder ähnlich sollten wir das auch lösen.

**Comment by Drakulix** [comment]
in jedem fall sollte da ein match statement bei uns schon mal hin. unwrap is evil :smiling_imp:

**Comment by msaehn** [comment]
you have the job.

**Comment by stilleben** [comment]
In Twee ist jede Variable erstmal mit null initialisiert, sofern man ihr nichts anderes zugewiesen hat. Also "0" und nicht das Wort.

**Comment by laerador** [comment]
@Drakulix Ich würde das gerne fixen, das klingt nach etwa

**Comment by msaehn** [comment]
dann sollten wir das vielleicht auch so machen. wobei wir da eventuell ein problem bekommen, da wir aktuell keine typ-änderungen vorsehen. spricht müsste dann ein eine 0 oder ein "0" geprintet werden, zcode trenn sowas ja nunmal.

beispiel für ein problem:

```
<<$var>>
// op_print_num(0)
<<set $var="123">>
// hier ist es nun plötzlich ein string
```

wenn wir sagen wie lassen keine typänderungen zu, müsste erst überprüft werden ob die variable irgendwo gesetzt wird, daraus den typ bestimmen und dann die variable auf 0 bzw. "0" setzen. oh je.

**Comment by fgr0** [comment]
kann man die Deklaration nicht einfach ignorieren? muss für `<<set $var="abc">>` die Variable schon existieren?

**Comment by msaehn** [comment]
in dem fall ist das kein problem. wenn $var schon existiert gibt die symboltabelle die entsprechende ID zurück, wenn es sie nicht gibt wird diese ID erzeugt, der typ festgelegt und "var" in der hashmap aufgenommen..

das geht aber andersherum nicht, denn da wissen wir den typ der variable gar nicht.

**Comment by felinira** [comment]
Moment, das verstehe ich nicht. Warum wollen wir denn Variablen printen können, bevor sie irgendwo gesetzt werden?

**Comment by msaehn** [comment]
ich weiß nicht ob wir das wollen, aber manche menschen in twee wollen es vielleicht. und in twee wird in dem fall 0 ausgegeben.
bzw. falls wir das verbieten (was ich ok fände), sollte eine gut lesbare fehlermeldung erscheinen.

**Comment by felinira** [comment]
Also das Ding ist, um rauszufinden, ob ne Variable schon benutzt wurde oder nicht und in welcher Reihenfolge, brauchen wir nen Control Flow im AST. Nunja, das Thema hatten wir schon :D

**Comment by msaehn** [comment]
außer halt wir setzen ebenso alle variablen die auftreten vorher auf 0. aber das ergibt die probleme von oben.

**Comment by felinira** [comment]
Ja eben, dann können wir den Typen halt nicht rausfinden.

**Comment by pothos** [comment]
Weiteres Problem:
Wenn in einer anderen Passage eine Variable gesetzt wird und wir in einer Passage sind, die die Variable nicht selbst initialisiert, sondern einfach so drauf zugreift, kann es zum Absturz kommen, wenn irgendwo in einer anderen Passage mal ein Typwechsel in der Symboltabelle erfolgt.
Zur Zeit gehen wir die Passages von oben nach unten durch und haben in der gleichen Linearität die Typwechsel in der Symboltabelle.

Zwei Alternativen:
Wir werfen einen Fehler, wenn wir oben beschriebenen Fall erkennen.
Oder steigen auf Boxed-Types um ;) – was ein ziemlicher Overhead an Organisation wäre.

**Comment by msaehn** [comment]
was spricht dagegen auf typwechsel innerhalb von variablen ganz zu verzichten? wenn die variablen nur einen typ haben, dann können wir sie auch beim start sinnvoll initialisieren.

**Comment by pothos** [comment]
genau, daher war ja der erste Vorschlag, dann einen Fehler zu werfen

**Comment by msaehn** [comment]
achso, ja. aber den fehler könnten wir ja schon im compiler werfen, nicht erst in zcode. oder meintest du das? ich wäre auf alle fälle dafür. auf den overhead können wir meines achtens verzichten. dann lieber schauen was wir ansonsten für probleme haben.

**Comment by pothos** [comment]
Also wenn wir in der Symboltabelle einen Typenwechsel bemerken, können wir den Fehler werfen. Falls Leute aber diese Variable immer neu in der Passage initalisieren statt passagenübergreifend einen Zugriff zu machen, brauchen wir aber nicht unbedingt einen Fehler schmeißen, da es klappen müsste.

**Comment by pothos** [comment]
Mittlerweile denke ich, wir sollten voraussetzen, dass Variablen bei ihrem ersten Auftreten mit dem richtigen Typen initialisiert werden. Also die einfachste Lösung wäre dann in der Start-Passage, wenn es Leuten zu unübersichtlich ist, das erste Auftreten zu finden.

**Comment by pothos** [comment]
Andererseits könnten wir davon ausgehen, dass – da twine dafür 0 setzt – Leute von uninitialisierten Variablen erwarten, dass sie 0 sind. D.h. wenn der Compiler darauf stößt, kommt sie als Int in die Symboltabelle und eine neue globale Variablen-ID wird zugewiesen.

**Comment by felinira** [comment]
Aber wenn sie ein String ist dürfte sie von Twine auf "" gesetzt werden oder?

**Comment by msaehn** [comment]
ne. twine gibt unitialisierte variablen immer mit 0 aus. egal ob sie später zu einem string werden.

**Comment by pothos** [comment]
Behoben durch dynamische Typen.
