### ISSUE TITLE
no easteregg flag for compiler

### ISSUE THREAD

**Issue by berikobama** [Drakulix/zwreec#139]

**Comment by msaehn** [comment]
das gibt es schon durch die configs: easter_egg

die config wird auch zu codegen weitergegeben, aber eben noch nicht nach zfile.
in zfile müsste in end() die funktion "routine_check_more()" deaktiviert werden und in "routine_check_links()" folgende zielen deaktiviert werden:

```
ZOP::JE{local_var_id: 0x01, equal_to_const: 129, jump_to_label: "system_check_links_jmp".to_string()},
ZOP::Jump{jump_to_label: "system_check_links_after".to_string()},
ZOP::Label{name: "system_check_links_jmp".to_string()},
ZOP::Call1N{jump_to_label: "system_check_more".to_string()},

ZOP::Label{name: "system_check_links_after".to_string()},
```

**Comment by pothos** [comment]
Ist umgesetzt durch eine leere check_more(), daher wurden die Zeilen nicht deaktiviert
