### ISSUE TITLE
Move codegen into extra module in backend and out of ast

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/zwreec#142]
Keine Ahnung, ob ich das die nächsten Tage selber machen, wenn ich anfangen sollte assigne ich mich. Falls jemand vorher Lust hat nur zu, mich stört das nämlich total. ^^

**Comment by pothos** [comment]
Da es eher ästhetischer Natur ist, würde ich vorschlagen, das erst am Ende zu machen, weil das ständige Umschieben von Code beim Mergen extrem aufwändig ist.

**Comment by benj-zen** [comment]
Wurde ja schon gemacht
