### ISSUE TITLE
Expressions vom Parser zum AST weitergeben

### ISSUE THREAD

**Issue by benj-zen** [Drakulix/zwreec#145]
Expressions müssen vom Parser in den AST übersetzt werden, sodass es dann z.B. folgende Struktur gibt.

```
1 + 4 * $var
```

```
TokExpression
|----> TokOp(+)
         |----> TokInt(1)
         |----> TokOp(*)
                  |----> TokInt(4)
                  |----> TokVar($var)
```

Gehört zu #110.

**Comment by msaehn** [comment]
ich bin mir aktuell nicht sicher, ob der ast so wie abgebildet erstellt werden kann,schließlich ist es infix und nicht prefix. und aktuell wird immer die 1 vor dem "+" gematcht. da die grammatik in dem moment aber ja nicht weiß, was danach kommt, muss die 1 erstmal hinzugefügt werden. ich vermute es wird eher sowas wie:

```
TokExpression
|----> TokInt(1)
|----> TokInt(+)
         |----> TokInt(4)
         |----> TokOp(*)
                   |----> Tokvar(var)
```

o.ä.

**Comment by msaehn** [comment]
wie benj vorgeschlagen hat, werden wir versuchen folgenden baum zu implementieren: http://programmers.stackexchange.com/questions/254074/how-exactly-is-an-abstract-syntax-tree-created

dafür werden alle sachen in dem expression erstmal auf einer ebene an dem baum eingefügt und bevor der ast traversiert wird, werden nochmal alle expressions durchgegangen.

**Comment by msaehn** [comment]
hier fehlt noch #157 (Logische Operatoren) und #155 (Klammern für Expressions)

**Comment by msaehn** [comment]
ist alles implementiert.
