### ISSUE TITLE
Expression vom AST in Z-Code übersetzen

### ISSUE THREAD

**Issue by benj-zen** [Drakulix/zwreec#146]
Die Baumstruktur der Expressions muss traversiert werden und mit temporären Variablen in Z-Code ausgewertet werden.
Gehört zu #110.

**Comment by pothos** [comment]
Ist nur ein Vorschlag: Fall die Auswertung eines Vergleiches t3 := t1 <= t2 ohne Labelsprünge gemacht werden soll, könnte es mit einem relativen Sprung so hier aussehen:
t3 := -1;
JG t1 t2 →RelJump+1;  // springt hinter den nächsten Befehl, falls !(t1 <= t2) also t1 > t2
inc t3;
inc t3;  // also ist für t1 <= t2 hier t3 == 1 und für den Fall t1 > t2 hier t3 == 0

**Comment by benj-zen** [comment]
so in etwa hab ichs gelöst ^^( #158 )

**Comment by benj-zen** [comment]
bloß mit label

**Comment by pothos** [comment]
Genau, und deshalb falls wir es ohne so viele Labels machen wollen, dann wäre das hier mein Vorschlag.

**Comment by benj-zen** [comment]
Gehen RelJumps in Z-Code?

**Comment by pothos** [comment]
Die Label-Jumps werden später eh in relative Jumps umgewandelt ;)

**Comment by pothos** [comment]
(außer für Routine-Calls mit packed addr)

**Comment by msaehn** [comment]
ist vielleicht nur etwas sauber mit den labels, weil wir uns sicher gehen, dass es so funktioniert. bei expliziten angaben müsste ja erst berechnet werden wieviel bytes es nun wirklich vor bzw. zurückgeht.

**Comment by pothos** [comment]
Ist schon ok, wie es gerade ist. Wäre dafür aber auch leichter, Tests zu schreiben, wenn wir keine Label-Jumps drin haben, sondern Relative.

**Comment by msaehn** [comment]
ist mit #158 implementiert.
