### ISSUE TITLE
Rustlex apparently now works on Stable

### ISSUE THREAD

**Issue by fgr0** [Drakulix/zwreec#149]
Apparently, the original [rustlex](https://github.com/LeoTestard/rustlex) has received some major updates and just released version 0.3.0 three days ago. Among those changes is support for Rust 1.0 Stable _alongside_ the known nightly-support (https://github.com/LeoTestard/rustlex/commit/3a04853f562a6cadfc34fb1f5acc49d813e9468e). 

The `README.md` of rustlex now contains the following section about stable support:

> #### Stable
> 
> On the stable channel, you have to use [syntex](https://github.com/erickt/rust-syntex) to first perform code generation and then
>  `include!()` the produced code into your project.
> 
> Your `Cargo.toml` should look like that:
> 
> ``` toml
> [package]
> name = "your package"
> version = "0.0.0"
> build = "build.rs"
> 
> [build-dependencies]
> rustlex_codegen = { version = "*", features = ["with-syntex"] }
> syntex          = { version = "*", optional = true }
> 
> [dependencies]
> rustlex_codegen = { version = "*", features = ["with-syntex"] }
> ```
> 
> You will need to write a `build.rs` file. This file is automatically called by
> `cargo` before the build (according to the `build` variable in the `Cargo.toml`
> file). In our case, it will use syntex to process your code and call RustLex's
> code generation:
> 
> ``` rust
> pub fn main() {
>     extern crate syntex;
>     extern crate rustlex_codegen;
>     use std::env;
>     use std::path::Path;
> 
>     let mut registry = syntex::Registry::new();
>     rustlex_codegen::plugin_registrar(&mut registry);
>     let src = Path::new("src/foo.in.rs");
>     let dst = Path::new(&env::var_os("OUT_DIR").unwrap()).join("foo.rs");
>     registry.expand("", &src, &dst).unwrap();
> }
> ```
> 
> Replace `foo.in.rs` by the name of the file in which you will use RustLex. Note
> that all its submodules are processed with it, so you don't need to add them as
> well even if they also contain calls to the RustLex macro.
> 
> This will generate a file called `foo.rs` (or however you named it) in Cargo's
> `OUT_DIR`. To use this file, add something like this somewhere in your project
> (for example in a `foo.rs` file placed alongside `foo.in.rs`):
> 
> If you want to build a project using RustLex that can be built using either
> stable or nightly, you can write a portable `Cargo.toml` file using features,
> and use the `#[cfg()]` attribute in your `build.rs` and the rest of your code to
> make it build using both versions. You can check out the [test project](http://github.com/LeoTestard/RustLex/tree/master/codegen/tests/Cargo.toml/) for
> `rustlex_codegen` for an example.

The question for us, specifically @Farthen, who forked rustlex, is, if we want to update to the new and stable rustlex version.

If we don't want to use the stable version, the git repository of rustlex also contains currently a new (nightly) version 0.3.1, @Farthen's fork is on version 0.2.7, and since I can't open Issues on that fork, I'll ask here, if we will merge the changes from rustlex' master back into the fork. I don't totally understand the impact of all the changes between 0.2.7 and 0.3.1, besides the nightly support.

One problem might be, that @Farthen forked from [kali's rustlex](https://github.com/kali/rustlex), the changes I am talking about happened on the original project from [LeoTestard/rustlex](https://github.com/LeoTestard/rustlex).

**Comment by Drakulix** [comment]
Interessant. Wenn wir das machen wollen, sollte es möglichst schnell passieren, falls wir Sachen im Lexer fixen müssen durch die Änderungen zu Version 0.3.1.
Wenn wir nicht auf stable wollen (benutzen wir andere nightly features?) sollten wir nicht updaten denke ich. Der Fork funktioniert und ich sehe keinen Nutzen kurz vor "Fertigstellung" uns damit Probleme einzuhandeln.

**Comment by felinira** [comment]
Ich bin auch dagegen, hier nen Schnellschuss zu machen. Wenn sich jemand anschauen will, was das für Implikationen hat, gern. Aber ich mag lieber jetzt die Sachen machen, die uns wirklich davon abhalten, twee files zu bauen.

**Comment by msaehn** [comment]
als ziel am ende mit stable arbeiten zu können, fände ich schon schön. aber es gibt definitiv noch genügend aufgaben die höhere priorität haben.

**Comment by felinira** [comment]
Siehe #189. Wenn der drin ist kann das hier zu.
