### ISSUE TITLE
ast.rs aufsplitten

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#154]
die ast.rs nähert sich gerade der 1000zeilen marke. das wird langsam sehr unübersichtlich und sollte deswegen aufgesplittet werden.
vorschläge:
-z.b. alle structs-implementierungen in extra dateien.
-gen_zcode wäre in codegen.ts wohl eh viel besser aufgehoben.

dies sollte nach möglichkeit passieren, wenn mal nichts am am ast verändert wird. (was wohl zeitigstens soweit ist, wenn die expressions implementiert sind)

**Comment by benj-zen** [comment]
Ja, bin auch auf jeden Fall dafür. Expressions dürften heute fertig werden.

**Comment by fgr0** [comment]
klingt gut, aber: Ich würde nicht die Struktimplementierungen auslagern. Zumindest nicht alle. Wenn man Konsequent da durch geht und alles, was zum Codegen gehört rausnimmt (also `gen_zcode`, und die ganzen Structs, die dazu gehören wie `Symboltable`), dann wird die `ast.rs` wieder relativ klein, und dann sollten auch die ganzen Structs und deren Implementation, die zum AST gehören (wie z.B. `ASTNode` oder `AST` in der Datei bleiben.

**Comment by msaehn** [comment]
ist mit #167 implementiert
