### ISSUE TITLE
Klammern für Expressions implementieren

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#155]
klammern gehören wohl ebenso zu expressions, diese fehlen aber. es müsste wohl in etwa folgendes implementiert werden:
-im parser.rs die parse-tabelle bezüglich klammern implementieren
-darauf achten, dass die klammern innerhalb einer expression-ebene landen
-in expressionparser.rs die klammern implementieren.

**Comment by felinira** [comment]
Hihi, das ist so ein bisschen wie dieses else if oder? ^^

**Comment by msaehn** [comment]
diese expressions sind einfach doch komplizierter als gedacht... aber klammern sollten gehen. vor allem der  expressionparser muss angepasst werden. (außer der ll(1) parser macht es mit den klammern nochmal komplizierter.. ich hoffe aber nicht.)

**Comment by msaehn** [comment]
ist in #173 implementiert.
