### ISSUE TITLE
Zcode Tests

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#160]
In Zcode gibt es aktuell nur ein paar Tests. Seit der Umstrukturierung der Op-Codes sollte jeder Op-Code explizit getestet werden. Dafür könnte mit einem Assembler für jeden Op-Code die entsprechenden Bytes erzeugt werden und dann in unseren Tests überprüft werden.

**Comment by berikobama** [comment]
ich würde mich dran machen, wenn alle branches gemerged sind die zcode verändern

**Comment by berikobama** [comment]
implementiert in #172
