### ISSUE TITLE
Zur Zeit werden nur 9 Links unterstützt

### ISSUE THREAD

**Issue by pothos** [Drakulix/zwreec#181]
Wenn wir auf Buchstaben a-z umsteigen, können wir mehr als 9 Links auswählen.

**Comment by Drakulix** [comment]
oder einfach mit enter bestätigen und auch längere zahlen akzeptieren? Finde ich intuitiver.

**Comment by pothos** [comment]
oder 0-9 und erst ab dann a-z, so hätten wir 36
