### ISSUE TITLE
Compilehindernisse

### ISSUE THREAD

**Issue by pothos** [Drakulix/zwreec#192]
Hier die bisher erfolgreichen Twee-Dateien inkl. laufendem Z-Code:

https://www.dropbox.com/sh/lk6jes5e8eolzyj/AABKl6h-sI6BM8fDftVe22GUa?dl=0

Sachen mit checkbox sollten jetzt ohne Probleme durchlaufen:
- [x] Führende > bei Sätzen
- [x] Variable initalisieren
- [x] BOM ignorieren
- [x] HTML
- [x] HTTP-Links
- [x] style-passage
- [x] IMG
- [x] Dynamische Typen
- [x] Uninitialisierte Variablen

**Comment by msaehn** [comment]
hast du mit force oder ohne probiert?
die variablen-problematik ist ja in #137 letz endlich drin. führendes ">" klingt schon nach bug, sollten wir vielleicht erstellen?
wie ist das mit passages neu schreiben gemeint? sind da die twee-dateien "fehlerhaft"?

**Comment by pothos** [comment]
Ohne force.
Einfach die Zeile nochmal neu hingeschrieben, müsste ich im diff nachschauen, was genau da war.

**Comment by msaehn** [comment]
oft gibt es probleme mit unicode-zeichen die ganz am anfang stehen. wir können aber ja nicht jedes mögliche unicode-zeichen in das regex aufnemen. hat irgendeine person eine idee?

**Comment by Drakulix** [comment]
Eventuell mehr Patches an Rustlex, damit der damit besser klarkommt?

**Comment by msaehn** [comment]
TokFormatBulList ist aktuell ebenso ein problem. da das "\* text" auch so ganz gut als bulletlisteneintrag erkennbar ist, sollten wir das im lexer vielleicht erstmal deaktivieren.

**Comment by pothos** [comment]
TokFormatBulList rauszunehmen klingt sinnvoll

**Comment by pothos** [comment]
http-Links machen Probleme, da die zwei Strägstriche im Lexer als Beginn eines Italic-Formatierungsblock erkannt werden.

**Comment by stilleben** [comment]
Letzteres könnte man mit einem `let HTTP = "http://";` lösen.

**Comment by felinira** [comment]
Es gibt auch irgendwo ganz okaye http regexe. dann könnten wir urls rausfiltern oder so.

**Comment by felinira** [comment]
Also die Sache mit den Encodings können wir überhaupt nicht ändern. Sollen wir irgendwie erkennen, was das Encoding von einem random text file ist oder wie? Das ist zwar möglich, aber nicht sicher und sehr schwer… Und anscheinend gibt es noch keine rust libraries. Wir supporten halt nur UTF-8. Das sollte doch ne okaye Einschränkung sein…

**Comment by Drakulix** [comment]
Wir können die Datei einfach als String einlesen (Rust das "erkennen" und wandeln in UTF-8 also machen lassen) und diesen dann in was strikteres mit dem Rustlex klarkommt wandeln mit zB: https://github.com/lifthrasiir/rust-encoding

**Comment by felinira** [comment]
Rust kann encodings != utf-8?

**Comment by Drakulix** [comment]
Ich glaube. ^^'

**Comment by felinira** [comment]
Ich glaube nicht ^^. Ich glaube aber, dass glauben uns hier nicht weiter hilft…

**Comment by msaehn** [comment]
wir sollten auf alle fälle eine sinnvolle fehlermeldung wie "vermutlich ist die datei falsch encodiert" ausgaben, genauso wäre es gut wenn es in usersr readme.md steht, dass wir aktuell nur utf8 texte unterstützen.

**Comment by stilleben** [comment]
```
führendes > entfernen bei Sätzen
```

Scheint ein Bug zu sein, ein > sollte eigentlich Start_Char sein dürfen.. habe das im #230 gefixt.

```
Variable initalisieren
```

siehe #137

```
Start passage oder auch andere passages nochmal neu reinschreiben (Kodierung?)
```

siehe #195

```
HTML, Weblinks, style-passage und IMG entfernen
```

bereits gefixt

```
TokFormatBulList rauszunehmen klingt sinnvoll
```

bereits gefixt

```
http-Links machen Probleme, da die zwei Strägstriche im Lexer als Beginn eines Italic-Formatierungsblock erkannt werden.
```

bereits gefixt

---

=> Kann das hier zu? Für die noch offenen Punkte gibt es eigene Vorgänge.

**Comment by pothos** [comment]
Aktuell sind es noch uninitialisierte Variablen, die Probleme machen. Das würd ich halt als nächstes mit den Dynamischen Typen beheben und dann kann es meinetwegen zu.

**Comment by pothos** [comment]
Ah, "BOM entfernen" kommt noch mit hier rein.

**Comment by stilleben** [comment]
Wird das nicht jeweils in den Vorgängen #137 bzw. #195 behandelt/gefixt/wasauchimmer?

**Comment by pothos** [comment]
Dachte, das hier wäre so ein Meta-Ticket, an dem wir den aktuellen Stand festhalten. Kann aber auch sonst zu.

**Comment by stilleben** [comment]
Kann auch gern aufbleiben. Meine Erfahrungen mit Sammelvorgängen sind nur eher .. weniger gut, aber ich lass mich auch eines besseren belehren ;)

**Comment by felinira** [comment]
Wäre ganz nett, wenn jemand alles im ersten Post zusammenfassen könnte. Sonst wird das hier langsam wie ein ewiger Forenthread ^^

**Comment by pothos** [comment]
manchmal muss ich recht viele << endif >> macros entfernen, damit es kompiliert. vielleicht macht twine da zu viele…
