### ISSUE TITLE
Lexer und Kodierungen

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#195]
Der Lexer erkennt anscheinend gar keine Zeichen, sobald die Kodierung für ihn "nicht stimmt".
Es erscheint nur die Fehlermeldung:

```
[ERROR] zwreec::frontend::parser: (17:05:20) - [!!!] Critical Parser Error [!!!]NonTerminal:S is no allowed End
thread '<main>' panicked at 'Should generate jump to label "Start" but no such label exists', src/zwreec/backend/zcode/zfile.rs:335
```

Hier sollte entweder ausgegeben werden, dass die Datei nicht richtig gelesen werden kann, oder das keine Tokens gefunden wurden.

Zur Nachvollziehbarkeit:
Versuchen die Datei CastleDoomstone.twee aus should_work kompilieren.

bzw. es reicht auch schon:

```
:: Start
You stand before a massive castle, its walls and towers rising toward the sky. 
```

Und dann z.b. in Sublime mit file -> save with encoding -> utf16-BE

**Comment by Drakulix** [comment]
Könnten wir die Datei vorher als String einlesen, konvertieren und mittels Cursor nach rustlex füttern?

**Comment by felinira** [comment]
Dann könnten wir das encoding vielleicht auch erkennen und umwandeln lassen?

**Comment by berikobama** [comment]
https://github.com/lifthrasiir/rust-encoding
?

**Comment by msaehn** [comment]
problem ist auch bei dateien die mit BOM codiert sind, dass wir dann oft die passage in der 1. zeile nicht lesen und somit das ding der compiler die fehlermeldung "passage existiert nicht" ausgibt, was sehr verwirrend ist.

**Comment by msaehn** [comment]
bzw. das problem ist, dass bei kodierung mit BOM ein '\u{feff}" vor dem 1. zeichen hängt, der lexer das somit nicht mehr als zeilenanfang wertet.
kodierungen wie windows 1252 oder iso8859 scheinen keine probleme zu machen. nur welche mit BOM oder utf16 kodierungen. beides sollte aber wohl machbar sein?

**Comment by pothos** [comment]
Ich finde auch, dass wir nichts umwandeln müssen, sondern nur das BOM überspringen sollten, vielleicht per Dummytoken (Kommentartoken).

**Comment by msaehn** [comment]
ein dummytoken hätten den nachteil, dass es die zeichen für die token verschiebt.
den input zu öffnen, bom entfernen und verändert an den lexer zu übergeben macht aber ja irgendwie auch keinen sinn (oder?)
und dann bleibt nur noch in fn lex es irgendwie einzuarbeiten (aber wie?)
oder es in rustlex selber abzufangen.

**Comment by msaehn** [comment]
hier hat eine person in rust mal das gleiche problem: https://github.com/phildawes/racer/commit/a2d086aa905b62070a825b1c4f8d21e1ccea027b
in "src/racer/mod.rs"
aber so wie es dort gemacht ist würde es bei uns wohl nur im lexer gehen, weil wir dem lexer ja keinen string sondern einen bufreader übergeben.
wäre gut, wenn sich eine person vom lexerteam / menschen mit genug rust-wissen daran setzen würden

**Comment by pothos** [comment]
kann bei einem Dummytoken die Zeile gleichbleiben, dann wär es ja weniger schlimm?

**Comment by pothos** [comment]
oder als optionales Zeichen an den Anfang von PASSAGE_START?

**Comment by felinira** [comment]
Nen dummytoken sehe ich eh als unrealistisch an, weil rustlex auf so komische dinge wie diese BOM Teile vermutlich nicht matchen kann… Um genau zu sein könnte mein Unicode-Handling unter anderem damit ein Problem haben… Und halt generell das fehlende Unicode-Handling in Rustlex

**Comment by pothos** [comment]
Behoben im master.

**Comment by msaehn** [comment]
yep. wir sollten in der doku jedoch noch vermerken, dass wir nur utf8 twee-dateien unterstützen.
