### ISSUE TITLE
--help sollte die Liste aller Features haben

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#201]
Es gibt Optionen für Features aber die Featureliste ist sehr versteckt im output von --help -v direkt hintereinander. Es sollte eine extra Sektion mit Features geben und einem Erklärungstext, was die Features jeweils machen.

**EDIT**: Besser erklärt.

**Comment by pothos** [comment]
--help -v

**Comment by felinira** [comment]
Nein, da steht nicht die Liste der Features. Da steht nur, wie Features abgeschaltet und angeschaltet werden können.

**Comment by pothos** [comment]
Achso, also eine Erklärung, was sie sollen?

**Comment by felinira** [comment]
Naja einmal das aber auch eine Liste mit den Features, die es überhaupt gibt. Da steht momentan keine. Es gibt nur Doku über -N und -F, aber nicht, was für features ich dahinter schreiben kann.

**Comment by felinira** [comment]
Ah, jetzt hab ich die Liste doch gesehen. Die ist aber wirklich versteckt. Das könnte prominenter sein. Und halt auch sagen, was sie jeweils tun.

**Comment by msaehn** [comment]
fände ich auch gut. aktuell muss ich (bei manchen features) immer im quellcode nachschauen wie ich sie nutzen muss^^

**Comment by pothos** [comment]
force-unicode fügt keine Zeichen zur Unicode-Translation-Table hinzu, sodass zstrings immer nur aus zscii bestehen und unicode nur über den opcode für print_unicode ausgegeben wird (bei längeren Folgen von Unicodezeichen, werden sie als Strings ähnlich wie zstrings Länge > 3 hinter alle Funktionen ausgelagert, sonst wird direkt in der Funktion das Zeichen ausgegeben)
