### ISSUE TITLE
Geschwindigkeit des Compilers

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#209]
Wie Kai schon in #General meinte, wird der ganze Kompiliervorgang bei großen Dateien sehr langsam.
Hier mal ein paar genauere Daten (alle Tests mit abyss_final2.twee, die selber 229kb groß ist).
Ingesamt braucht der Compiler bei mir etwa **5-7 Minuten.**

Es zeigt sich, dass das Problem wohl in Zcode liegt, genauer bei den Jumps. In der Datei gibt es 1778 Sprünge bei 391 Labels. Wenn in add_jump bzw. add_label in zfile.rs nur die **2** folgenden Zeilen auskommentiert:

```
self.jumps.push(jump); bzw.
self.labels.push(label);
```

benötigt ein Durchlauf nur noch **2 Sekunden.**

Problem an den jumps ist nicht die eine Funktion die am Ende alle Jumps schreibt, sondern wohl folgende Konstrukte in write_zop:

```
let old_jumps: Vec<Zjump> = self.jumps.clone();
let old_labels: Vec<Zlabel> = self.labels.clone();
...
for label in self.labels.iter() {
    if !old_labels.contains(&label) {
        new_labels.push(label.clone());
    }
}
for jump in self.jumps.iter() {
    if !old_jumps.contains(&jump) {
        new_jumps.push(jump.clone());
    }
}
```

da wir new_labels nur zu testzwecken benötigen, bin ich dafür das irgendwie noch bis Do zu entfernen. von 5min auf 2sek ist ein Test-feature nicht wert.

**Comment by Drakulix** [comment]
Ist das mit Release oder Debug Build? (cargo build --release)
Diese langsamen Code-Stellen ließen sich so wie ich das sehe auch stark optimieren.

**Comment by felinira** [comment]
Es gibt sowas, das nennt sich HashMap. Vielleiiiicht könnte uns die hier helfen ^^

**Comment by msaehn** [comment]
beides mit debug. die codezeilen könnten praktisch auskommentiert werden. es würde alles bis auf einen test noch funktionieren.
das problem hier ist, dass die funktion die jumps zurückgibt, die "neu" sind. dafür wird für jeden ZOP die komplette Liste der Jumps durchlaufen.
Falls wir diese Labels trotzdem bräuchten, würde es wohl reichen wir überprüfen erstmal den vector auf die länge und nur falls sie unterschiedlich ist gehen wir die liste durch. oder ganz rauslassen.
