### ISSUE TITLE
Doppeltes Einbinden der Utils & nicht exportiere Log-Macros 

### ISSUE THREAD

**Issue by fgr0** [Drakulix/zwreec#21]
Nach meinem Verständnis sind `src/lib.rs` und `src/main.rs` zwei unterschiedliche Targets (Crates), weswegen eins auch `extern create zwreec` in der `src/main.rs` benutzen muss. Damit werden alle public Funktionen/Module eingebunden. Allerdings benutzt die `main.rs` im Moment auch folgenden Aufruf, welcher unnötig/unsinnig ist, weil das Utility-Modul bereits über `zwreec::utils` eingebunden werden (als _externe_ library). 

``` .rust
#[macro_use]
pub mod utils;
```

Der Aufruf bindet das Utility-Modul ein zweites mal ein, was wenig Sinn ergibt und nicht sein muss. Da das Modul bereits eingebunden wird, kann `pub mod utils` entfernt werden und `#[macro_use]` beim Einbinden der externen Library benutzt werden:

``` .rust
#[macro_use]
extern crate zwreec;
```

**Aber**: Dabei fällt auf, dass die Log-Macros im Moment **nicht** nach außen exportiert werden, da das Entsprechende Flag fehlt. Daher muss zusätzlich zu den Änderungen oben auch folgendes Flag an jede Makrodeklaration geschrieben werden:

``` .rust
#[macro_export]
macro_rules! log_info {
    ($($arg:tt)*) => (::utils::log::try_log(::utils::log::LogLevel::INFO, format_args!($($arg)*)));
}
```

**Comment by felinira** [comment]
Hm, verstehe. Kannst du versuchen, das mal so zu lösen, wie du es dir gedacht hast und nen PR zu machen?

**Comment by fgr0** [comment]
Kann ich machen, werde aber erstmal #20 fertig schreiben.

**Comment by fgr0** [comment]
Related to #22. 

Will be obsolete, when Log-Utils are rewritten.

**Comment by Drakulix** [comment]
Fixed with #25

'''rust
#[macro_use] extern crate log;
'''
sollte in jedem crate alle macros zugänglich machen.

utils::logger with nur noch im main crate importiert, was nach (http://doc.rust-lang.org/log/log/index.html#in-libraries) und (http://doc.rust-lang.org/log/log/index.html#in-executables) empfohlen wird.
