### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#212]
Dieser Issue ist dafür da, zu tracken, wo überall die Dokumentation schon ausreicht und wo noch Arbeit nötig ist. Wenn ihr irgendwo etwas anders seht als ich, ändert es gern :)
## Binary

Ist so wie ich das einschätzen kann fertig.
## Frontend
- [x] mod.rs
- [x] lexer.rs
- [x] rustlex.in.rs - Regeln und Regexe sollten jeweils Kommentare bekommen. Header oben.
- [x] parser.rs
- [x] ast.rs - Größtenteils Text oben fehlt und einzelne Funktionen sind nicht dokumentiert
- [x] expressionparser.rs
- [x] evaluate_expression.rs - Header und viele Funktionen fehlen
- [x] codegen.rs - Manche Funktionen haben noch keinen Docstring
## Backend
- [x] mod.rs - Beschreibung des Moduls und Beispielverwendung. Siehe frontend.rs
- [x] zcode/mod.rs - Siehe oben. Da wir das eh zusammenführen wollten wäre das ein guter Zeitpunkt
- [x] op.rs - Funktionen sind bis auf wenige Ausnahmen gut dokumentiert, es fehlt noch Header oben
- [x] zbytes.rs
- [x] zfile.rs - Der Header ist ein bisschen klein, manche Funktionen sind nicht dokumentiert
- [x] ztext.rs
## Config
- [x] mod.rs
## Utils
- [x] mod.rs - Beschreibung und usage des moduls
- [x] error.rs
- [x] extensions.rs - Header
- [x] ~~file.rs - Header~~

**Comment by Drakulix** [comment]
Wird utils/file.rs irgendwo überhaupt noch benutzt?

**Comment by msaehn** [comment]
@Drakulix meines achtens nein., könnte also weg.

**Comment by felinira** [comment]
Ach so, wenn ihr hieran durch irgendwelche PRs was ändert wäre es cool, wenn ihr die entsprechenden Checkboxen setzt…

**Comment by Drakulix** [comment]
hab utils fast fertig. niemand bitte anfangen.

**Comment by msaehn** [comment]
mag  jmd. diese header-texte schreiben, die noch fehlen? die funktionen würde ich dann zur not kurz beschreiben, wenn sich niemand findet. am besten wäre es natürlich, wenn die personen die die funktion geschrieben haben auch dokumentieren.
