### ISSUE TITLE
Log Level ist private

### ISSUE THREAD

**Issue by fgr0** [Drakulix/zwreec#22]
In der aktuellen Implementation ist `LOG_LEVEL` privat, d.h. es ist _nicht_ möglich aus der `main.rs` heraus das maximale Log Level zu setzen:

``` rust
fn main() {
    // set default log level
    utils::log::LOG_LEVEL = utils::log::LogLevel::WARN;
...
```

erzeugt folgenden Fehler:

```
src/main.rs:20:5: 20:26 error: static `LOG_LEVEL` is private
src/main.rs:20     utils::log::LOG_LEVEL = utils::log::LogLevel::WARN;
                   ^~~~~~~~~~~~~~~~~~~~~
src/main.rs:55:9: 55:30 error: static `LOG_LEVEL` is private
src/main.rs:55         utils::log::LOG_LEVEL = utils::log::LogLevel::VERBOSE;
                       ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
```

Das verhindert im Moment die Implementierung von eines `--verbose` Flags in #20.

**Comment by Drakulix** [comment]
statics können eh nicht mutable sein. Das gilt als unsafe. Ich gucke bei Zeiten, ob ich das schöner lösen kann.

**Comment by fgr0** [comment]
Du könntest dir ja wie in Slack erwähnt, die Log-Facade/env-logger als Beispiel nehmen

**Comment by Drakulix** [comment]
oder einfach die log-facade nutzen. es war ja ganz schön, das zur übung selber zu basteln, aber das ding sieht halt einfach praktischer aus.

**Comment by fgr0** [comment]
Die Log-facade logged aber selber nicht, sondern stellt AFAIK nur die Macros zur Verfügung, d.h. wir brauchen immer noch jemanden der das Gegenstück zur Facade implementiert.

Der Grund, warum Rust das so (kompliziert) macht, liegt wohl darin, dass jede Library (z.B. getopts) die Log-Facade benutzen kann, ohne selbst einen Logger zu implementieren. Sobald wir dann in unserem Projekt eine Implementation der Log-Facade zur Verfügung stellen, kann jede externe Library die wir benutzen, unsere Log-Implementation verwenden. 

Das klingt auf jeden Fall etwas komplexer, weil eins sich sowohl in die Log-Facade als auch in deren Implementierung einlesen muss --- **wenn** ich das so richtig verstanden habe.

**Comment by Drakulix** [comment]
Ah okay, das ist interessant. Wie stellen also eine Implementierung der Facade zur Verfügung und jede Library kann die über das einheitliche Interface benutzen. Das ist mal ne schöne Lösung für das Problem, dass du irgendwann tausend verschiedene Logger hast, wenn das Projekt größer wird und damit die Liste an Abhängigkeiten.

Ich werde mir das bei Gelegenheit anschauen und implementieren, das sollte dann auch dieses Problem hier fixen. Wenn es schon ein einheitliches Interface gibt, sollten wir das auch verwenden.

**Comment by pothos** [comment]
In diesem Fall ist es aber doch nicht so tragisch, wenn das eine global schreibbare Variable ist, falls davon ausgegangen werden kann, dass es entweder keine zwei parallelen Schreibvorgänge gibt oder gleichzeitige Schreibvorgänge keine korrupten Daten hinterlassen, was bei einem geschriebenen Wert wohl der Fall ist. In sonstigen Fällen kann auch der Zugriff per Mutex etc abgesichert werden.

**Comment by fgr0** [comment]
http://doc.rust-lang.org/log/log/index.html

Das sollten vermutlich alle lesen, zumindest die ersten Abschnitte um die Benutzung von Log zu verstehen. Für @Drakulix steht hier auch drin, wie die Facade implementiert wird. 

Dazu würde ich sagen, dass wir uns auf die Verwendung der Loglevels einigen sollten (Welches LogLevel wofür verwendet werden sollte)

**Comment by Drakulix** [comment]
Alles gefixt mit #25.
Log Level kann am Anfang via Logger Initializer einmalig gesetzt werden.
Wenn das nicht den Anforderungen entspricht oder nicht funktioniert => bitte reopen.
