### ISSUE TITLE
Bools geben Zahlen aus und keine strings

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#227]
Wenn in Twine ein bool ausgegeben wird, wird "true" oder "false" ausgegeben. Wir geben 0 für false und alle anderen Zahlen für true aus.

**Comment by pothos** [comment]
Ich würd vorschlagen, die Variablentypen in die Laufzeit zu verschieben, das macht einfach mehr Sinn und löst auch das Problem mit der Initialisierung und den Typenwechseln.

**Comment by msaehn** [comment]
ich finde ja, dass das mit 0 und 1 anstatt true/false kein bug ist, sondern eher künstl. freiheit;)
es gibt ja ganz viele sachen wo wir uns anders verhalten als twee.
wir müssten halt dann den typen der variable in zcode abbilden und dafür eigene print-routinen schreiben.
vermutlich kann da kai am besten einschätzen wie lange das dauern würde.
