### ISSUE TITLE
Silently und nobr makro noch nicht implementiert

### ISSUE THREAD

**Issue by benj-zen** [Drakulix/zwreec#231]
`<<silently>>` und `<<nobr>>` sind bis jetzt nur im Lexer enthalten.
Sollte aber kein Problem sein die zu übersetzen.

Eigentlich nur so quasi:

```
match (TokText(text))
   if !silently:
      print text
```

**Comment by pothos** [comment]
und Newlines unterdrücken. Könnte das an den FormattingState rangehängt werden?
