### ISSUE TITLE
Umsetzung für TokHeading fehlt

### ISSUE THREAD

**Issue by stilleben** [Drakulix/zwreec#232]
Bisher wird TokHeading noch nicht richtig in zcode umgesetzt. Das Token macht ab dem Parser Probleme.

Das Token bekommt eine Zahl mitgeliefert, die die Größe des Headings angibt. In der offiziellen Twee-Doku gibt es drei Größen, es geht anscheinend aber auch mehr.

Wie könnte man das in zcode umsetzen? Kann man die Schriftgröße ändern oder wollen wir einfach alle Überschriften fett machen?

**Comment by felinira** [comment]
Also soweit ich das verstehe ist es einmal möglich, Text bold, italic, fixed width und "inverse". Inverse macht die Hintergrundfarbe zur Vordergrundfarbe. Das könnte ich mir noch am ehesten vorstellen. Dann kann Z-Code noch verschiedene Farben im Vorder- und Hintergrund. Das wars aber auch, verschiedene Fonts gibt es nicht. Ließe sich glaube ich alles problemlos implementieren.

**Comment by Drakulix** [comment]
+1 für inverse

**Comment by felinira** [comment]
Wir können das auch kombinieren. Zum Beispiel: Überschriften sind immer inverse, die größte Überschrift ist bold und inverse, dann kommt kursiv und inverse, dann nur inverse. Oder sowas.
