### ISSUE TITLE
Beispieladventure

### ISSUE THREAD

**Issue by pothos** [Drakulix/zwreec#239]
https://www.dropbox.com/sh/lk6jes5e8eolzyj/AABKl6h-sI6BM8fDftVe22GUa?dl=0

**Comment by msaehn** [comment]
theor. ist das doch fertig, wenn wir das spiel in das textadventure mit übernehmen, oder? im grunde ist in beiden ja auch alles, was wir können. höchstens vielleicht noch etwas unicode... aber das ist auch nicht soo wichtig. oder gibt es noch etwas, was wir unbedingt übernehmen sollten?

**Comment by pothos** [comment]
Ich würd am Mittwochabend probieren, das in einer Datei zusammen zu fassen, sodass es einen flüssigen Übergang gibt, oder?

**Comment by msaehn** [comment]
klingt gut. wenn du zwit hast könntest du noch ein confirm bei "Q" einbauen, das würde da ganz gut passen.
