### ISSUE TITLE
Feedback einarbeiten

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#242]
- [x] Es gibt keine Linux 32-Bit executable - kümmern wir uns nächstes Release drum
- [x] Aufruf ohne Argumente sollte eine Hilfe anzeigen, wenn stdin leer ist
- [x] Es sollte keine output-Datei erzeugt werden, wenn der Compiler nicht durchläuft, weil die Argumente falsch sind.
- [x] LICENSE sollte angepasst werden
- [x] Die Installation bzw. die Notwendigkeit von cargo sollte noch mal für OS X beschrieben werden bzw erklärt, dass rustup auch unter OS X funktioniert.
- [x] Erklärung von Twee in der Doku

**Comment by kinnla** [comment]
Hi Finn,

> Aufruf ohne Argumente sollte eine Hilfe anzeigen, den zweiten Teil der Mail habe ich nicht verstanden: "Selbiges bei ./zwreec zwreec. Erwartetes Verhalten: Fehlermeldung, Abbruch, keine Output-Datei erzeugt.”
> Gemeint war, dass eine output Datei (a.z8) erzeugt wird, auch wenn der Compiler nicht durchläuft. Mein Beispiel dafür: ./zwreec zwreec (Natürlich kann der Compiler seine eigene Binary nicht kompilieren). Erwartetes Verhalten: Fehlermeldung, Abbruch, keine Output-Datei.

+++ till

**Comment by kinnla** [comment]
> generate-sample-zcode scheint komisch dokumentiert zu sein (oder so?)

Mein Fehler! Kann geschlossen werden

**Comment by msaehn** [comment]
haha, hätten wir doch nur auf weitere installations-tipps verzichtet und nur die curl-zeile hingeschrieben, dann wäre das wohl nicht passiert^^
aber ja, wenn wir was von brew erzählen (denn in unserer doku steht ja nichts zu brew) oder von packages schreiben, sollten wir am besten auch nochmal genauer darauf eingehen.

sollte aber ja alles lösbar sein.

**Comment by felinira** [comment]
@kinnla Ah, okay, das klärt es, danke.

**Comment by stilleben** [comment]
> Die weiterführende Doku im Wiki ist hilfreich für Z-Code-Neulinge. **Ein paar Worte zu Twee würden noch passen.**

Eventuell können wir das noch mit reinnehmen.

**Comment by felinira** [comment]
Stimmt, das hab ich beim Übernehmen übersehen.

**Comment by fgr0** [comment]
Ich hab das [Release](https://github.com/Drakulix/zwreec/releases/tag/v0.4.0) angepasst und an die Dateien `-amd64` angehängt um zumindest schonmal zu signalisieren, dass wir im Moment nur 64-bit Releases haben.

**Comment by msaehn** [comment]
kann man das releasen eigentlich irgendwie automatisieren? wäre ganz praktisch. gerade weil wir ja auch in das release noch andere sachen bauen.

**Comment by pothos** [comment]
Eigentlich brauchen wir die Beispieldateien im Release nicht.

**Comment by fgr0** [comment]
Release könnte durch Travis automatisiert werden. Aber er würde dann vermutlich mit jedem Masterpush ein `nightly` bauen. Aber ich kann mal schauen.

**Comment by msaehn** [comment]
theor. bräuchten wir ja nicht immer ein release. aber vielleicht automatisiert wenn es so ein release-tag gibt? -travis wird vermutlich nicht für osx compilieren können. oder?
bzw. ein script wäre ja auch gut. denn wir müssten den kram aktuell ja schon unter 3 system bauen, was schon nicht so toll ist.

**Comment by pothos** [comment]
Müssen wir denn Archivdateien nehmen oder reicht es nicht, direkt die binaries hier zu speichern?

**Comment by fgr0** [comment]
die Archiv-dateien sind doch gar nicht das problem, dass problem ist, dass wir travis beibringen müssen, nach einem erfolgreichen `cargo test` noch ein `cargo build --release` zu machen und dafür auch noch weitere Umgebungen (OSX) zu starten.

Da wir aber releases nur brauchen, wenn wir ein Release machen, finde ich das nicht so wichtig eigentlich.

**Comment by pothos** [comment]
Ich meinte, es ist weniger Aufwand, ein Release zu machen, wenn es nur darum geht, die binaries hochzuladen. Aber gern auch automatisiert, wenn es irgendwie klappt ;)

**Comment by fgr0** [comment]
Wegen automatisch angelegten outputfile: Ist schwierig, außer wenn das Outputfile wirklich erst am Ende angelegt wird, was ich in so weit als Problematisch sehe, als dass wir dann Kompilieren (Zeit brauchen), nur um am Ende festzustellen, dass wir nicht schreiben können (weil Fehler oder kein `-w`). 

Möglichkeit wäre: 
1. Überprüfen, ob OUTPUT existiert/ob `-w` angegeben wurde (legt Datei nicht an)
2. Temporäre Datei anlegen
3. Mit temporärer Datei als OUTPUT kompilieren
4. Temporäre Datei verschieben/umbenennen

Dabei gibts aber ein Problem: zwischen Schritt 1 und Schritt 4 kann die Datei angelegt werden, und wenn dann `-w` _nicht_ angegeben wurde, bekommen wir einen merkwürdigen Konflikt.

**Comment by felinira** [comment]
@laerador Hier ging es ja gar nicht darum, dass der kein output file erstellt, wenn er nicht durchläuft, sondern nur, wenn ein Syntaxfehler in den Argumenten ist. Das was du vorgeschlagen hast wäre natürlich auch praktisch, ließe sich wohl am einfachsten lösen, wenn in ein u8 Array geschrieben würde und erst am Ende das dann ausgegeben wird.

**Comment by fgr0** [comment]
Achso, ja das kann ich beheben. Morgen. :D

**Comment by Drakulix** [comment]
Wer kann sich btw um die 32-bit linux executable kümmern? in meinen repos gibt es keinen 32-bit rustc, wenn jemand schon ein 32-bit system noch irgendwo hat wäre das praktischer.

**Comment by msaehn** [comment]
ich hab zuhause noch irgendwo noch ein 32-bitubuntu rumstehen... 
aber am liebsten wäre es mir z.b. wenn das travis machen könnte. dann könnten alle 3 releases autom. erstellt werden, ohne das bei uns 3 personen auf 3 verschiedenen computern möglicheweise auf unterschiedliche weisen ein release erstellen.

**Comment by Drakulix** [comment]
@laerador Ginge das mit Travis nicht eventuell, wenn wir einen Tag setzen, dass der beim mergen das sieht und nur dann einen Release Build macht?

EDIT:
http://docs.travis-ci.com/user/deployment/releases/ ???
