### ISSUE TITLE
log module should be moved out of utilities

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/zwreec#26]
Da das log module in utils ist, wird es vom zwreec crate (lib.rs) eingebunden und compiled werden, sobald das utils module noch für irgendwas anderes benutzt wird außer logging. Das ist überflüssig weil es nur von main.rs benutzt werden sollte.

Temporär könnte es einfach ein neues "top-level module" werden (also /log, statt /utils/log), weil ich aber glaube main wird noch mehr utility-stuff bekommen wird, schlage ich vor hierfür eine bessere Struktur aufzubauen. Jemand ne gute idee? main-utils ist mir zu lang.

**Comment by fgr0** [comment]
Interessantes Problem. Hm. Ich würde es auch erstmal einfach nach `/log.rs` verschieben. allerdings benutzt dein Logger doch im Moment `files.rs` oder? Das wiederum wird ja am Ende auch "nur" von der main benötigt und ich würde das eigentlich auch gerne in einem Ordner haben wollen. Da in Utils im Moment sowieso nichts weiter drin ist, wollen wir dann noch einfach erstmal utils nicht in der lib.rs einbinden? 

Ich frage mich gerade, ob es mit Cargo möglich ist, 2 libraries zu verwalten, hab dazu aber mit 2 min googlen nix gefunden. _wenn_ das geht, dann könnte eins einfach eine zweite _cmd_-Library machen, die alle Dinge für die Main.rs enthält

**Comment by felinira** [comment]
Warum sollte nur main.rs loggen dürfen? Wenn der Compiler nen Fehler wirft sollte das ja schon auch in der Konsole erscheinen.

**Comment by Drakulix** [comment]
@laerador Nein ich benutze nur das File Dings aus der Rust Standart Library, nicht das files.rs.
Zwei targets sind auch möglich,hab auch schon überlegt den ganzen logger kram in einen eigenen crate zu packen, weil ich da jetzt schon dead_code warnings hatte, weil da logger drin sind, die wir aktuell noch nicht benutzen.

@Farthen siehe mein letzter kommtar #21

**Comment by fgr0** [comment]
Ich hab tatsächlich eine vielleicht gute Idee:

Ich hab mir grad relativ viele Rüst-Projekte hier auf Github angeschaut, um raus zu bekommen, wie die dieses Problem lösen. Bei vielen Repos (z.B. bei [Cargo](https://github.com/rust-lang/cargo) selbst) gibt es einen Ordner `src/bin/` in dem sich dann alle Binary-related Mods befinden. Dieser Ordner wird dann in der `Cargo.toml` entsprechend definiert. 

Hier mal ein Beispiel:

``` .tree
zwreec
├── Cargo.lock
├── Cargo.toml
├── LICENSE
├── README.md
├── src
│   ├── backend/...
│   ├── bin/
│   │   ├── main.rs
│   │   ├── log.rs
│   ├── frontend/...
│   ├── lib.rs
│   └── utils/
│       ├── file.rs
│       └── mod.rs
└── tests
    └── lib.rs
```

Die `Cargo.toml` müsste dann so erweitert werden:

``` .toml
[package]
name = "zwreec"
version = "0.1.0"
authors = [ ]

[lib]
name = "zwreec"
path = "src/lib.rs"

[[bin]]
name = "zwreec"
path = "src/bin/main.rs"
```

(Warum das `[[bin]]` doppelte Klammern haben muss, würde ich auch mal gerne wissen)

Das führt auf jeden Fall dazu, dass Executable und Library sauber von einander getrennt werden können.

**Comment by fgr0** [comment]
Das scheint sogar Cargo-Default zu sein: [http://doc.crates.io/guide.html#cargo-conventions](http://doc.crates.io/guide.html#cargo-conventions)

**Comment by Drakulix** [comment]
Dann bin ich für einen Wechsel

**Comment by fgr0** [comment]
Ich habe jetzt 2 leicht unterschiedliche Projektlayouts, die sind beide auch soweit lauffähig und mit `cargo test` getestet.

Die erste Variante verschiebt die `main.rs` und das `logger` Modul nach `src/bin` sowie die `file.rs` nach `utils/file.rs`.

```
.
├── Cargo.lock
├── Cargo.toml
├── LICENSE
├── README.md
├── src
│   ├── backend/
│   ├── bin
│   │   ├── logger/
│   │   └── zwreec.rs
│   ├── frontend/
│   ├── lib.rs
│   ├── utils
│   │   ├── file.rs
│   │   └── mod.rs
└── tests/
```

Die zweite Variante baut darauf auf und geht noch einen Schritt weiter: alle Module/Dateien die zur Library gehören werden in einen entsprechenden Unterordner zur Übersichtlichkeit geräumt:

```
.
├── Cargo.lock
├── Cargo.toml
├── LICENSE
├── README.md
├── src
│   ├── bin
│   │   ├── logger/
│   │   └── zwreec.rs
│   └── zwreec
│       ├── backend/
│       ├── frontend/
│       ├── lib.rs
│       └── utils/
└── tests/
```

Noch ein paar Anmerkungen zu den Änderungen die ich gemacht habe:
- Ich habe die `main.rs` nach `zwreec.rs` umgenannt, weil nach Konvention in dem `src/bin` Ordner mehrere binäre Targets liegen könnten und daher wird die Datei meistens nach dem endgültigen Namen der Executable benannt. Das war bei uns vorher `zwreec_bin` was ich in diesem Zuge auch auf `zwreec` geändert habe. Rein praktisch gibt es kein Problem, wenn Library und Binary den selben Namen haben.
- Für das Binary (und damit auch für `logger`) werden keine Tests mehr ausgeführt. Das verhindert, dass diese für uns relativ nutzlosen `warn(dead_code)` Warnungen ausgegeben werden. Auch das scheint bei vielen Projekten Standard zu sein. Falls für das `logger` Modul Tests ausgeführt werden sollen, sehe ich 2 Möglichkeiten: Entweder es wird zurück in die Hauptlibrary verschoben und wir finden uns damit ab, dass es auch in der Library ist, oder @Drakulix macht ein eigenes Repo/eigene Crate für den Logger auf---meiner Meinung nach hätte er das sogar verdient.
- Ich schlage vor, `src/utils` nach `src/util` zu ändern. Dieses "s" am Ende macht mich leicht verrückt. (Mein Gedankengang dabei: Das ist unser _Utility_-Modul, Singular macht imho mehr sinn---aber das ist Geschmacksache)
- Alle Entscheidungen die ich bis jetzt getroffen habe, sind größtenteils vom Layout des Cargo-Repositories und der Cargo-Doku beeinflusst.

Ich schreibe das hier und habe noch keinen Pull Request aufgemacht, damit wir uns absprechen können welche der beiden Varianten (if any) wir verwenden wollen. Grundsätzlich ist aber beides soweit fertig, ihr könnt euch dass dann nochmal genauer anschauen, sobald ich den Pull Request geöffnet habe. Ich selbst bevorzuge **Variante 2**, da sie zur Übersichtlichkeit/Aufgeräumtheit des Projektes beiträgt.

**Comment by Drakulix** [comment]
Bevorzuge ebenfalls 2.
Was spricht gegen eine weitere Repo? Hatte daran nämlich auch schon überlegt und würde das logger crate vielleicht sogar unter dem namen "BasicLogger" oder so auf crates.io publishen.
Kann ja immer noch bestandteil unseres Projektes sein.

**Comment by fgr0** [comment]
@Drakulix nichts spricht dagegen, bis darauf, dass es halt deine Entscheidung wäre und nicht meine/unsere :) (Und das ich keine Ahnung habe, wie eins Dinge auf crates.io submitted)

**Comment by Drakulix** [comment]
naja ich beanspruche nicht alleinige rechte an dem code.
