### ISSUE TITLE
zcode Unicode Translation Table

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#34]
"Richtige" Unicode-Unterstützung für zcode implementieren. Dafür muss die translation-table erstellt und in (extension_addr +3) die Adresse dieser Tabelle gesetzt werden.
Ebenso muss die encode-Methode in ztext entsprechend erweitert werden.

**Comment by felinira** [comment]
#72 hat unicode print unterstützt. Kann das jetzt zu oder wollen wir den Bug umbenennen in "richtige" Unterstützung mit translation table? Brauchen wir das? Was hat es für Vorteile, was für Nachteile?

**Comment by msaehn** [comment]
umbenennen ergibt sinn
weg sollte das noch nicht. #72 hat den nachteil, dass für jedes unicode zeichen ein opcode erstellt wird (4 mal 8 bits), was ziemlich ineffizient bezüglich dem verbrauchten speicher ist. einfache sonderzeichen (wie z.b. ä, ö, ü) (vgl z-machine doku) können auch ohne den extra opcode mit in der kodierung von einen string für "print" eingebaut werden, bräuchten dort aber nur rund 18 bits (bzw. 4 mal 5-bits, wobei 3 mal 5bits in 2 bytes passen).

**Comment by pothos** [comment]
Kann nun geschlossen werden, richtig?

**Comment by msaehn** [comment]
ja, ist ja mit #125 implementiert.
