### ISSUE TITLE
New compiler flags

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#42]
We need compiler flags

**Comment by fgr0** [comment]
Vorschläge welche Flags wir so benötigen?

**Comment by msaehn** [comment]
zcode-debug flags:
- über alle vorkommenden texte iterieren, damit sichtbar ist ob alle zeichen korrekt angezeigt werden
- labels printen
- ...

**Comment by msaehn** [comment]
ich hätte kerne ein compilerflag, was mir die möglichkeit bietet direkt eine funktion aufzurufen um zcode auszuführen. z.b. in zcode/mod.rs die "temp_create_zcode_example()" function

**Comment by msaehn** [comment]
wie ist hier der stand, wäre ganz pratisch um nicht immer temporär methoden einzufügen um z.b. nur in zcode etwas zu testen.

**Comment by fgr0** [comment]
Es wäre Hilfreich, wenn es eine (vollständige) Liste gibt, mit folgenden Angaben: 
1. Type: Toggle/Value
2. Werterange: boolean, i32, 0-100, "Bernd"
3. Default: An, Aus, 5
4. Wo soll diese Option überprüft werden?

Im Moment habe ich einfach noch zu wenig überblick, was überhaupt für Optionen gewünscht sind, und an welcher Stelle sie hin sollen. Es müsste ja jeder den Top-post editieren können, es wäre toll, wenn jeder dort rein mit den 4 Punkten schreibt, was eins gerne hätte. Dann kann ich mir auch überlegen, wie eins das Implementiert und dann mache ich das auch zügig.

**Comment by msaehn** [comment]
- zcode test (schaltet eine function an um explizit eine methode aufzurufen die nur zcode-functions ausführt)
  - toggle
  - bool
  - default aus
  - mir eigentlich egal wo. aktuell wäre lib.rs praktisch. dort könnte sie z.b. einfach zusätzlich laufen oder sie hängt sich in den ganzen prozess inklusive output file, dann könnte lexer, parser etc übersprugnen werden

**Comment by fgr0** [comment]
Wie wird bestimmt, welche zcodes ausgeführt werden sollen? Warum soll das ein flag und nicht einfach ein Test werden?

**Comment by msaehn** [comment]
es soll eigentlich nur eine function aufgerufen werden, aktuell z.b. "temp_create_zcode_example" in zcode/mod.rs
es soll kein test werden, weil es ja kein richtig und falsch geben wird. es soll eine z8-datei erstellt werden, die unabhängig vom lexer, parser, ... sich verhält. wenn wir irgendwann alle (tm) opcodes impelementiert haben und diese laufen, kann das auch wieder entfernt werden. aber aktuell hinkt parser und ast den opcodes hinterher, wir wollen aber ja trotzdem schauen ob sie richtig funktionieren, bzw. testen ob eine bestimmte funktion genau das macht wie erhofft.

vielleicht gibt es dafür auch einen anderen weg, aber ich dachte 1 compilerflag wäre ganz praktisch.

**Comment by felinira** [comment]
Würde das auch einfach erstmal als flag implementieren. Sollte am einfachsten gehen. Sowas wie --debug-zcode-build oder --test-zcode, --generate-sample-zcode äh ihr könnt es euch denken. Nen Test wäre auch denkbar, aber grad wäre es wohl eher praktisch, da nen einfachen hook zu haben, der sich drum kümmert, damit das backend getestet werden kann.

**Comment by fgr0** [comment]
oki.
