### ISSUE TITLE
Hyperlink Emulation & Passagenverlinkung

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#43]
Das Klicken auf Links in HTML-Seiten wird passend in Z-Code emuliert und korrekt verarbeitet.
Passagen können verlinkt und mit Hilfe von emulierten "Klicks" in der Z-Code Umgebung aufgerufen werden.

**Comment by msaehn** [comment]
Die Auswahl des jeweiligen Links soll durch die Eingabe von Zahlen möglich emuliert werden.
Ich sehe 3 verschiedene Möglichkeiten:
- keine eindeutige Verbindung zwischen Zahl und Link, 1 bedeutet einfach "1. Link", 2 bedeutet "2. Link", ...
- die Zahl der jeweiligen Links im Text nach dem Link ausgeben, z.b. linktext [1]
- die Zahlen werden ganz unten mit den Link-Bezeichnungen ausgeben:
  - [1] linktext1; [2] linktext2; [3] linktext3; ...

Ebenso sollte über eine einheitliche Formatierung von Links nachgedacht werden. Eine bestimmte Farbe würde sich anbietet, besser ist aber vielleicht der zcode-style "reverse", da es dann auch ohne Farbunterstützung des Interpreters funktionieren würde.

**Comment by msaehn** [comment]
Hier mal ein Minimalbeispiel für die Passageverlinkung:

```
::Start
link1: [[p1]]
link2: [[p2]]
::p1
back to start: [[Start]]
::p2
p2 text
```

**Comment by msaehn** [comment]
der ast würde in etwa dann so aussehen:
![ast_link](https://cloud.githubusercontent.com/assets/1397415/7809319/8cc75276-0399-11e5-8782-0ca81db554e5.png)

**Comment by msaehn** [comment]
die traversierung des ast müsste in etwa so aussehen

```
Nodetype                | action
------------------------+---------------------------------------------
S                       | childs(); routine("checklinks")
Passage:                | routine("Passage.name", 0); childs();
                        | call_1n("checklinks");
                        | 
TokPassageLink          | op_set_text_style(state.bold, true, state.mono, state.italic);
                        | op_print("TokPassageLink.name"));
                        | op_call_2n(("add_link", TokPassageLink.name);
                        | op_set_text_style(state.bold, true, state.mono, state.italic);

// routine has 2 lokal variables, frst is the pressed-key
// snd is the address of the next jump (from the stack)
routine("checklinks", 2):
    label("checklinks_loop");
    // saves the key in $1
    op_read_char($1);

    // to compare asci codes (1-key ist ascii 49)
    // with count of links
    // var = var - 48
    op_sub($1, 48, $1);

    // check if links exist, if not loop
    op_jl($16, $1, "checklinks_loop");

    op_dec($1);

    // loads the address of the next routing
    // in $2
    op_loadw(0, $1, $2);

    // resets the count of links
    op_store($16, 0);

    op_call_1n($2);


// global var $16 counts the current links
routine("add_link", 1);
    // stores the value of $1 to the address 0+2*$16 
    op_storew(0, $16, $1)
    // inc the count links
    op_inc($16);
    // returns true
    op_ret(1)
```

**Comment by msaehn** [comment]
leider wird das wohl doch nicht so einfach wie oben dargestellt.
denn via if / else, display, ... müssten links in abhängigkeit von variablen erstellt werden können.
meine beste idee ist es wohl eine extra z-code routine zu schreiben, die nach jeder passage aufgerufen wird. dafür müssten die adressen der anderen passage-routinen in variablen zur laufzeit gespeichert werden und dann in abhängigkeit der tastatureingabe aufgerufen werden.

**Comment by msaehn** [comment]
wir können jedes mal wenn ein link angezeigt wird die adresse der verlinkten routine auf den stack pushen und gleichzeitig in einer globalen variable speichern wieviele links in der der aktuellen passage genutzt werden.
dann könnte eine extra routine nach jeder passage einfach den stack abarbeiten und endsprechend auf die die tastatureingabe reagieren. if-else sollte damit problemlos funktionieren und auch display mit ein paar umwegen möglich machen.

**Comment by msaehn** [comment]
ist mit #73 erstmal abgeschlossen, -> close
