### ISSUE TITLE
Variablen

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#44]
Variablen können in Twee Code gesetzt und verwendet werden. Dies kompiliert zu Z-Code und wird äquivalent umgesetzt.

Requires:
- [x] #62 zcode op print_num
- [x] #65 zcode op store
- [x] #86 symboltabelle
- [x] #85 einfache variablenzuweisungen

**Comment by msaehn** [comment]
zahlen in zcode zu speichern ist nicht so das problem. der text müsste aber vorher in den speicher geschrieben werden und dann mit print_addr aufgerufen werden. wie das ist mit text, der z.b. erst zur laufzeit erstellt wird, dass weiß ich leider (noch?) nicht.
Hier noch ein Minimalbeispiel.

```
::Start
<<set $var1 to "string example">>
<<set $var2 to 123>>
<<set $var3 to true>>
variable set:
<<$var1>>
<<$var2>>
<<$var3>>
```

**Comment by felinira** [comment]
Z-Code kann keine Floats. Wir wollen die irgendwann vielleicht emulieren, aber jetzt gerade sollten wir das erstmal nicht supporten.

**Comment by msaehn** [comment]
bei dem printen gibt es ein problem:
in zcode sind es 2 unterschiedliche funktionen für das printen von text und integer. twee hat diese unterscheidung aber nicht.
wir müssten -am besten in der symboltabelle uns merken um was es sich bei der variable für einen typ handelt und falls twee typen miteinander mixt den kompeliervorgang abbrechen.
also falls z.b. einmal da steht:

```
$var = "123"
$var = 123
```

bzw. falls eine person einen anderen vorschlag hat, immer her damit.

**Comment by msaehn** [comment]
laut backlog müssten wir die variablen übrigens gar nicht printen können, sondern nur "verwenden"^^
schön wäre es aber wohl, wenn wir das noch schaffen würden. integer zu printen geht ja schon, da fehlt nur die anbindung ast->zcode
(aber am besten gleich mit der typ-speicherung durchführen)

**Comment by Drakulix** [comment]
ist es in twee erlaubt die selber variable mit mehreren typen zu benutzen? sollten wir das dann nicht auch können?

**Comment by msaehn** [comment]
erlaubt ist das schon, aber ich wüßte nicht wie wir das in twee abbilden, außer für jede variable noch den typ in eine extra variable zu speichern. der typ könnte sich dann ja zur laufzeit -in abhängigkeit der eingabe- ändern.

**Comment by Drakulix** [comment]
oder halt die variable intern neu benennen, sobald sich der typ ändert.

**Comment by msaehn** [comment]
das klingt zumindest irgendwie machbar.

**Comment by Drakulix** [comment]
ist dann ja praktisch ne neue variable. das könnte man eventuell schon im parser abfangen und im ast entsprechend anlegen.

**Comment by msaehn** [comment]
ja, oder in der symboltabelle, die weiß ja zb. welche variablen es gibt und müsste sich eh irgendwie den typ merken. dann könnte diese einfache 2 unterschiedliche ids zurückgeben.
aber sowas wie:

```
if $var_bool {
  $var = 123
} else {
 $var = "123"
}
print $var
```

wäre wohl trotzdem sehr nervig. oder man merkt sich irgendwie wo in der schleife lang gegangen wurde...

**Comment by Drakulix** [comment]
ja das stimmt schon, schleifen hatte ich nicht bedacht. so ein dreck.

**Comment by msaehn** [comment]
ist fertig, da es für den string-teil ein neues issue gibt: #113
