### ISSUE TITLE
Macro und Twine Funktionen Übersicht

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#46]
Erstellen einer Übersicht der Makros (aus Twine-Wiki), mögliche Umsetzung, Sinnhaftigkeit einer Umsetzung, Wichtigkeit der Umsetzung in Z-Code, etc...

**Comment by msaehn** [comment]
zcode sicht:

Makros:
- if-else: kein problem
- set: kein problem
- remember: in zcode möglich, aber vielleicht eher unwichtig
- forget: siehe oben
- print: mit einschränkungen möglich (problem ist wohl eher, dass expressions kompliziert werden können)
- display: wohl nicht so einfach in zcode zu realisieren (bzw. es müsste wohl analysiert werden welche passage display aufruft und welche passagen von display genutzt werden. wenn wir für jede passage eine routine nutzen, müssten wir zwischen routinen hin und herspringen,...)
- actions: wird müsten uns in zcode merken, welche links gedrückt wurden, das könnten eventuell irgendwann viele variablen werden
- choice: ähnlich wie actions.
- nobr: kein problem
- textinput: eigentlich kein problem
- radio: geht nur simuliert, sollte aber nicht schwerer als passage-verlinkung sein
- checkbox: siehe radio
- button: kein problem
- silently: kein problem

**Comment by stilleben** [comment]
Unser Lexer sollte eigentlich mit keinem Makro ein Problem haben, man müsste sie nur spezifizieren und hinzufügen. 

Folgendes haben wir in der Twee-Definition festgelegt, was erkannt werden muss:

if, else, set, print, display, actions, choice, nobr, silently

---
1. _remember_ und _forget_ können wir noch zusätzlich machen, wir wussten zum damaligen Zeitpunkt nicht, ob man Variablen in zcode dauerhaft speichern kann.
2. _textinput_, _radio_, _checkbox_, _button_ haben wir rausgenommen, weil es äquivalente Funktionen wie prompt() gibt und wir ebenfalls nicht wussten, inwiefern man das darstellen kann. Wenn _textinput_ und _button_ problemlos möglich sind, dann können wir die beiden gerne noch mit reinnehmen. 
3. Für _print_ haben wir sowieso ausgeschlossen, dass sowas wie `<<print "<<print $"+$var1+$var2+">>”>>` (Makroverschachtelung) erkannt wird. Welche Einschränkungen würdet ihr denn noch brauchen?
4. Bei _display_, _actions_ und _choice_  müsste man sich nochmal mit den anderen Gruppen zusammensetzen, ob wir das streichen können, wenn gewünscht.

**Comment by stilleben** [comment]
![screen shot 2015-06-10 at 13 20 48](https://cloud.githubusercontent.com/assets/11980960/8081244/99723384-0f73-11e5-9b0c-08f654f95ac3.png)

erste Version

Sinnhaftigkeit habe ich am Vorkommen der Makros in Twee-Dateien abgeleitet. 
Die grüne Markierung sind die Makros, auf die wir uns nach Auswertung der Tabelle als erstes bzw. verstärkt konzentrieren sollten. Generell sind aber alle aufgezählten Makros möglich.

Kommentare? Ich habe keine Ideen für weitere Spalten...

**Comment by msaehn** [comment]
als übersicht sieht das auf alle fälle sehr gut aus. ich weiß auch nicht ob du mehr spalten brauchen solltest, ist doch so ok.
ich schreib gleich noch was zu den functions in twee, ob / wie die in zcode umgesetzt werden könnten.

**Comment by stilleben** [comment]
Ist nun die Frage, ob sie Functions auch haben wollten... An sich zählen sie nicht zu Makros, sondern zu Expressions.

Machen können wir's, ist nicht wirklich ein großer Aufwand.

**Comment by msaehn** [comment]
dachte weil auf dem "wunschzettel" von till/leon steht: "Makro und Twine Funktionen Übersicht"

bis jetzt unterstützen wir eh keine funktionen in der grammatik, oder?

hier die liste:
zcode umsetzung:
-either(): wenn random implementiert ist, sollte das nicht schwer sein
-random(): ist in zcode schon pmplementiert
-rot13(): geht schon, aber kompliziert, weil es viele teile in zcode betrifft. es müssten wohl eigene print-routinen geschrieben werden, strings komplett anders gespeichert werden
-previous(): geht
-visited(): für jede passage würde eine variable benötigt werden, das könnte eventuell irgendwann viel werden. oder es wird in einem array gespeichert, aber es würde ja auch da platz wegnehmen^^
-visitedTag(): ähnlich wie visited, aber einfacher, da es weniger tags gibt
-turns(): da die verlinkung aktuell zentral abläuft, sollte das recht einfach sein
-tags(): sollte gehen
-parameter(): das geht vermutlich schon irgendwie, aber leicht wäre es nicht
-confirm(): geht
-promt(): ähnlich wie textinput
-alert(): keinp roblem
-open(): geht nicht.

**Comment by stilleben** [comment]
![screen shot 2015-06-10 at 18 06 39](https://cloud.githubusercontent.com/assets/11980960/8087717/d5aeb0f6-0f9c-11e5-9721-8198926518b0.png)

![screen shot 2015-06-10 at 18 20 47](https://cloud.githubusercontent.com/assets/11980960/8087818/72f29ecc-0f9d-11e5-91e6-f6ad2023f13e.png)

Die Bilder und die .xlsx-Dateien sind auch im Slack/KVV hochgeladen.

Ich schließe mal.
