### ISSUE TITLE
Verzweigungen

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#53]
If-Else in Twee kompiliert und funktioniert in Z-Code. Erstmal nur mit Variablen.
- [x] #85 einfache variablenzuweisungen
- [x] #86 symboltabelle

**Comment by msaehn** [comment]
das minimalbeispiel wäre hier wohl:

```
::Start
before macro
<<set $var to 1>>
<<if $var == 1>>
if text
<<else>>
else text
<<endif>>
text after macro
```

**Comment by msaehn** [comment]
ein möglicher ast:
![ast_ifelse](https://cloud.githubusercontent.com/assets/1397415/7810182/21c52cd0-03a0-11e5-9299-4cff9121b05a.png)

**Comment by benj-zen** [comment]
Requires #85
