### ISSUE TITLE
Verwendung von Github Issue Labels

### ISSUE THREAD

**Issue by fgr0** [Drakulix/zwreec#55]
Ich hatte vorhin bei der Besprechung vergessen nachzufragen, aber prinzipiell sollten wir nochmal über die Verwendung von Labels nachdenken--welche wir benutzen wollen und welche Bedeutung diese dann für uns haben.

Ich fasse hier erstmal zusammen, welche Labels wir im Moment haben, wie _ich_ sie im Moment verstehe und zähle dann nochmal ein paar Labels auf, von denen ich denke, dass wir sie sinnvoll einsetzen können. Ich werde dann auch versuchen, eure Vorschläge hier nochmal zusammen zu fassen.

---

Status 21.05.2015:
- [backlog](https://github.com/Drakulix/zwreec/labels/backlog): Unser Sprint Backlog: Alle Issues die unseren (hoffentlich) aktuellen Milestone entsprechen
- [bug](https://github.com/Drakulix/zwreec/labels/bug): rel. eindeutig
- [duplicate](https://github.com/Drakulix/zwreec/labels/duplicate): Been there, done that
- [easy](https://github.com/Drakulix/zwreec/labels/easy): Ursprüngliche Idee waren Aufgaben, die _relativ_ einfach zu erledigen scheinen. Hat aber nicht wirklich zu deren Bearbeitung beigetragen mMn sondern sogar eher aufgehoben, da alle\* (*zumindest ich) sich gedacht haben, dass eins die vielleicht für andere lassen soll, anstatt sie einfach zu bearbeiten. (Bsp.: #24) -- würde ich also entfernen wollen
- [enhancement](https://github.com/Drakulix/zwreec/labels/enhancement): nicht sicher, was hiermit genau gemeint ist, vermute aber sowas wie _features_?
- [help wanted](https://github.com/Drakulix/zwreec/labels/help%20wanted): rel. eindeutig
- [invalid](https://github.com/Drakulix/zwreec/labels/invalid): überschneidet sich mMn mit _wontfix_ (s.u.)
- [project management](https://github.com/Drakulix/zwreec/labels/project%20management): Issues, die nicht Code-Related sind, wie z.B. diese hier. Damit können auch asynchron Entscheidungen im Team getroffen werden, ohne sich darauf verlassen zu müssen, dass alle in Slack aufpassen
- [question](https://github.com/Drakulix/zwreec/labels/question): rel. eindeutig
- [wontfix](https://github.com/Drakulix/zwreec/labels/wontfix): überscheidet sich mMn mit _invalid_

Das Label _easy_ würde ich entfernen wollen, dafür würde ich noch Labels hinzufügen wollen, die die Unterschiedlichen Teile des Codes beschreiben, z.B. _Lexer_, _Parser_, _Binary_, _Logger_. Dazu würde ich noch das generische Label _documentation_ hinzufügen, für alle Sachen, die genauere Dokumentation erfordern. Ansonsten, wenn mit _enhancement_ nicht sowas wie _feature_ gemeint ist, würde ich noch sowas hinzufügen, damit man schnell Issues findet, die sozusagen neuen Code erfordern.

Wenn wir uns auf eine Definition für die einzelnen Labels geeinigt haben, könnten wir diese ja auch mit in das Wiki zum Nachschlagen aufnehmen.

---

Gesammelte Vorsahläge:
- [x] Abschnittsspezifische Labels: `Lexer`, `Parser`, `Dokumentation`
- [x] Rust/Cargo/Git-Probleme: `Environment`
- [x] Sprachen: `twee`/`zcode`

**Comment by fgr0** [comment]
Eine weitere Idee wären Labels für die Priorität von Issues.

**Comment by msaehn** [comment]
so wie ich enhancement verstehe, geht es ehr um verbesserungen / erweiterung von aktuellen sachen? unter feature würde ich eher komplett neue sachen verstehen, wobei das wohl ähnlich ist.
wegen easy weiß ich nicht. du hast da natürlich recht, aber vielleicht ist es doch ganz gut etwas zu haben, was klar macht, dass dieses issue zu lösen wohl nicht sehr lange dauert.
eine einordnung bezüglich lexer / parser etc finde ich gut.

**Comment by fgr0** [comment]
Ich würde auch noch ein Label `env(ironment)` vorschlagen für Issues/Pull Request die mit Rust/Cargo/Git zu tun haben. Z.B. für Dinge wie #41 oder `.gitignore`-Änderungen

Auch möglich: `twee`/`zcode`

**Comment by msaehn** [comment]
ich würde twee und zcode als labels trennen. twee selber betrifft ja eher den lexer und teile außerhalb des programms (grammatik etc), zcode dagegen nur codegen und den zcode-modul.

**Comment by felinira** [comment]
Ich hab das mal so gemacht. Wenn es noch weitere Änderungsvorschläge gibt: Wieder aufmachen.
