### ISSUE TITLE
zcode op print_addr

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#61]
der op-code print_addr um z-encoded text von einer Speicheraddresse zu printen müsste für #44 implementiert werden.
es müsste vorher überprüft werden ob nicht print_paddr die zukunftssichere wäre.

**Comment by pothos** [comment]
der high memory kann nicht zur Laufzeit verändert werden, daher ist print_addr im Hinblick für Variablen auf jeden Fall nötig. Falls initiale Inhalte im high memory statisch hinterlegt werden, muss beim Ausgeben der Variable je nach der Speicheradresse, auf die sie aktuell zeigt, print_paddr oder print_addr genutzt werden.
http://inform-fiction.org/zmachine/standards/z1point1/sect01.html
