### ISSUE TITLE
"Start" Passage ist 1. Passage die ausgeführt wird

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#63]
Twee fängt immer mit der "Start" Passage an, diese muss aber nicht die 1. Passage im Twee-code sein.
Aktuell wird immer die 1. Passage als die Start-Passage gewählt.
Lösung: vor der Code-Erzeugung sollten alle Passages im AST durchgegangen werden, wenn es keine Start-Passage gibt, dann panic!(error bla).
Wird benötigt für #43

**Comment by kinnla** [comment]
schöner Testcase!

**Comment by msaehn** [comment]
am besten in zfile.rs in der methode "write_jumps" überprüfen ob alle existierenden labels / routinen einen sprung bzw. alle sprünge ein label / routine haben. den "Start"-sprung gibt es immer, die Start-routine kann aber fehlen..
