### ISSUE TITLE
Iterator stürzt bei Unicode ab

### ISSUE THREAD

**Issue by pothos** [Drakulix/zwreec#71]
War schon aufgetreten in #39 und ist nun wieder da, sogar nicht nur beim ersten Zeichen.

**Comment by msaehn** [comment]
beispiel zum testen:

```
::Start
Hellöo World, ''Yeah''.
And //italic// is possible too.
```

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [101, 108, 108, 246, 111, 32, 87, 111, 114, 108, 100, 44, 32], error: Utf8Error { valid_up_to: 3 } }', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:729
```

**Comment by felinira** [comment]
Dieser issue wird erst zu gemacht wenn jemand einen test case dafür geschrieben hat zusätzlich zum bug fixen!

**Comment by msaehn** [comment]
das problem liegt irgendwo in der lib.rs in der zeile:

```
let ast = frontend::parser::parse_tokens(tokens.inspect(|ref token| {
        debug!("{:?}", token);
    }).collect());
```

wobei das problem nicht im parser liegt, sondern wohl im iterator. (hab im parser allex auskommentiert und einen leeren ast zurückgegeben, trotzdem panict das programm)

**Comment by felinira** [comment]
Es könnte sein, dass wir hier über bytes iterieren, wir aber über graphemes iterieren sollten und der sich dann verschluckt, wenn er Zeichen > ein byte findet. Ich weiß grad nicht, was dafür eigentlich geändert werden müsste, aber das dürfte hier unser Problem sein, wenn ich das richtig verstehe.
