### ISSUE TITLE
Produziert kaputte z8 files

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#80]
Manchmal erstellt der compiler einfach Garbage. Ich kann das nicht wirklich sauber reproduzieren, aber jetzt gerade tut er bei mir genau das. Je länger der Text in der Passage bei mir ist, desto wahrscheinlicher ist es irgendwie, dass er sich irgendwann verschluckt. Dann kommen 1-2 Zeichen Garbage und dann fragte die Z-Machine nach MORE, was aber nach drücken von Return nicht mehr Text anzeigt.

Beispiel, was bei mir mehr oder weniger reproduzierbar failed:

```
::Start
This is a sample text with a very long line. This line is used to demonstrate that the compiler doesn't produce garbage if there is more than a few characters per line. As you can see everything is fine.
```

```
# cargo run tests/integration/sample/LongText.twee
     Running `target/debug/zwreec tests/integration/sample/LongText.twee`
# dfrotz ./a.z8
  This is a sample text with a very long line. This line is used to
  demonstrate that the compiler doesn't produce garbage if there is more than
  a few characters pera  l
***MORE***
***MORE***
***MORE***^C
```

**Comment by msaehn** [comment]
gibt es da auch ein problem mit anderen interpretern?

**Comment by felinira** [comment]
Ja, genau das gleiche wird im normalen frotz angezeigt. Andere Interpreter hab ich grad nicht zur Hand, wie hieß noch mal der eine, den wir sonst noch benutzt hatten?

**Comment by felinira** [comment]
Ich habe mal sample files in die Dropbox hochgeladen: `/Bugs/#80/test.twee` und `fail.z8`, damit das evtl genauer reproduzierbar ist. Es scheint irgendwie an der Länge der twee files bzw der resultierenden z8 files zu liegen.
