### ISSUE TITLE
Einfache Variablenzuweisung

### ISSUE THREAD

**Issue by benj-zen** [Drakulix/zwreec#85]
Um eine Verzweigung durchführen zu können, muss vorher eine Variable gesetzt werden.
Hierzu soll erstmal unterstützt werden:

```
<<set $var = 1>>
<<set $var = 0>>
```

und eventuell

```
<<set $var = true>>
<<set $var = false>>
```

**Comment by msaehn** [comment]
das hängt auch mit #44 zusammen.
ints können mit op_store schon gesetzt werden, für den ast->zcode wäre das wohl auch recht einfach. allerdings müsste wohl vorher noch eine symboltabelle angelegt werden, die die namenauflösung der variablen in twee zu ints macht (global hat den int bereich von 16-255, wobei aktuell in der globalen variablen 16 schon die anzahl der links gespeichert werden)

**Comment by benj-zen** [comment]
Bin dran und fast fertig.

**Comment by benj-zen** [comment]
Hab bis jetzt allerdings op_store_u8 verwendet. Gibts auch nen op der ganze ints speichert?

**Comment by msaehn** [comment]
du könntest ein op_store_u16 erstellen, was

```
let args: Vec<ArgType> = vec![ArgType::Reference, ArgType::LargeConst];
...
self.data.append_u16(value);
```

nutzt.
später müsste das dann nochmal sauberer umgesetzt werden, dafür wären aber wohl größere umsetzungen benötigt.

bzw. für ints sollte wohl dann immer der u16-teil genutzt werden und nur für bools oder wo definitiv klar ist, dass die zahl <256 ist...

**Comment by msaehn** [comment]
am besten das auch mit op_print_num_var testen..

ich sehe gerade, op_1 unterstützt aktuell noch keine LargeConst, weshalb das erst implementiert werden müsste.
