### ISSUE TITLE
Lexer parsed keine Tags

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#89]
Irgendwas ist kaputt beim Lexen von Tags. Ich weiß, wir brauchen die noch nicht, aber der Lexer supportet es, also teste ich es auch nach bugs. Input file:

```
::TagPassage [tag1 tag2]
Content
```

Output:

```
[TokPassageName("TagPassage [tag1 tag2"), TokText("Content")]
```

Erwartet:

```
[TokPassageName("TagPassage"), TokTagStart, TokTag("tag1"), TokTag("tag2"), TokTagEnd, TokText("Content")]
```

**Comment by felinira** [comment]
Nen Testcase (potentiell mit Fehlern) befindet sich auch in meinem branch feature/lexer-tests, dafür einfach die funktion tag_test auskommentieren in lexer.rs

**Comment by benj-zen** [comment]
Hmm, das liegt daran, dass wir im PassagenNamen "[" erlaubt haben, um bei Passagenlinks dem Twee-Verhalten gleich zu sein. Müsste man entweder doch wieder rausnehmen, oder ne andere Lösung finden.

**Comment by felinira** [comment]
Das verstehe ich nicht. "Bei Passagenlinks dem Twee-Verhalten gleich sein"?

**Comment by benj-zen** [comment]
Meine damit, dass Twee zum Beispiel beim Link

```
[[[Name]]
```

als Passagennamen "[Name" verwendet.
Unser Lexer hatte halt vorher ein Text-Token "[" erkannt, und danach einen Link zur Passage "Name".

**Comment by stilleben** [comment]
Orr, wir haben ja genau aus dem Grund eckige Klammern im Link-/Passagennamen in der Twee-Definition ausgeschlossen. Also gehört bei [[[Name]] das erste [ dann zum TokText, so wie es vorher war. Das war mein Fehler... sorry. 

Dann müsste eigentlich nur Commit 86859bd89f6709a0c8adcfcd67980e90f04d602c rückgängig gemacht werden - ich mach das mal.

**Comment by stilleben** [comment]
So, ist nun wie vorher. Finde ich in der aktuellen Situation am besten, weil am nähesten an unserer Tweedefinition.

Nochmal kurz eine Beschreibung des Verhaltens bei [] in Passagennamen/Linktexten:

```
::PassageName [[tag]
Bla
```

Abbruch des Compilevorgangs weil der Passagenname "PassageName [" lautet und das "[" hier nicht zulässig ist. Auch nicht "Passage[Name" oder sowas.

``` ::PassageName
Bla [[[Text]]
```

Korrekt, der TokText lautet "Bla [" und der Linktext "Text".
